# Generated by Django 4.0.4 on 2022-09-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='client status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_therapist',
            field=models.BooleanField(default=False, verbose_name='therapist status'),
        ),
    ]
