# Generated by Django 4.0.4 on 2022-09-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='user',
        ),
    ]
